const assetUrl = (path) => `${import.meta.env.BASE_URL}${path}`;

export const stages = [
  {
    id: 1,
    stageNumber: 1,
    date: "Sun 18 Oct",
    title: "Sa Batalla",
    distance: "82 km",
    elevation: "1,024 m",
    duration: "3:30",
    difficulty: "Intermediate",
    motivation: "Start strong.",
    routeLine: "Pollença · Alcúdia Bay · Santa Magdalena · Sa Batalla · Lluc · Pollença",
    briefing:
      "The week opens with a coastal rollout and quiet roads through the Albufera before the first real tests arrive. Santa Magdalena sharpens the legs; Sa Batalla becomes the camp’s all-in FTP and lactate effort, followed by the flowing Coll de Femenia descent home.",
    effort: "Build patiently through Santa Magdalena, then save the match you want to burn on Sa Batalla.",
    map: assetUrl("assets/routes/stage-1-map.jpg"),
    profile: assetUrl("assets/routes/stage-1-profile.png"),
    officialUrl: "https://www.sacalobra.cc/stage/1/",
    videoUrl: "https://www.sacalobra.cc/stages/video/stage-1-1920.mp4",
    sourceNote: "Camp sheet: 1,024 m. Current SCCC route overview: 1,014 m. Official profile: about 82.5 km.",
    climbs: [
      {
        name: "Santa Magdalena",
        category: "Cat 3",
        distance: "5.49 km",
        gradient: "6%",
        strava: "https://www.strava.com/segments/17911492",
      },
      {
        name: "Sa Batalla",
        category: "Cat 2",
        distance: "7.83 km",
        gradient: "5%",
        strava: "https://www.strava.com/segments/686221",
      },
    ],
    publicRoutes: [
      {
        provider: "Bikemap",
        label: "Pollença–Sa Batalla–Santa Magdalena",
        stats: "81.1 km · 1,024 m",
        match: "High match · GPX export may require Premium",
        url: "https://www.bikemap.net/en/r/8249474/",
      },
      {
        provider: "Ride with GPS",
        label: "Sa Pobla–Santa Magdalena",
        stats: "80.4 km · 743 m",
        match: "Partial preview · omits Sa Batalla",
        url: "https://ridewithgps.com/trips/41443813",
      },
    ],
  },
  {
    id: 2,
    stageNumber: 2,
    date: "Mon 19 Oct",
    title: "Randa & Felanitx",
    distance: "99 km",
    elevation: "1,290 m",
    duration: "4:00",
    difficulty: "Intermediate",
    motivation: "Climb steadily.",
    routeLine: "Pollença · Sineu · Randa · Porreres · Sant Salvador, Felanitx",
    briefing:
      "The first true endurance day follows quiet southern lanes across Mallorca’s farmland. Randa rewards disciplined threshold pacing, then Sant Salvador delivers a steep, exposed summit finish where the bikes go into the support van and every last match can be spent.",
    effort: "Smooth group work across the plains; measured threshold on Randa; empty the tank at Sant Salvador.",
    map: assetUrl("assets/routes/stage-2-map.jpg"),
    profile: assetUrl("assets/routes/stage-2-profile.png"),
    officialUrl: "https://www.sacalobra.cc/stage/2/",
    videoUrl: "https://www.sacalobra.cc/stages/video/stage-2-1920.mp4",
    sourceNote: "Camp sheet: 99 km / 1,290 m. Current SCCC overview: 95 km / 1,299 m. Official profile: about 94.5 km.",
    climbs: [
      {
        name: "Randa",
        category: "Cat 3",
        distance: "4.75 km",
        gradient: "5%",
        strava: "https://www.strava.com/segments/1098418",
      },
      {
        name: "Sant Salvador / Felanitx",
        category: "Cat 2",
        distance: "4.73 km",
        gradient: "7%",
        strava: "https://www.strava.com/segments/17577693",
      },
    ],
    publicRoutes: [
      {
        provider: "Ride with GPS",
        label: "Pollença–Randa–Sant Salvador",
        stats: "161.9 km · 1,761 m",
        match: "Core-route preview · includes a long return",
        url: "https://ridewithgps.com/trips/43444763",
      },
    ],
  },
  {
    id: 3,
    stageNumber: 3,
    date: "Tue 20 Oct",
    title: "Queen Stage",
    distance: "123 km",
    elevation: "2,349 m",
    duration: "5:30",
    difficulty: "Difficult",
    motivation: "Earn it all.",
    routeLine: "Pollença · Tofla · Orient · Honor · Sóller · Puig Major · Lluc · Pollença",
    briefing:
      "Five climbs accumulate before the week’s only hors catégorie ascent. The terrain keeps asking questions through Orient and Sóller, then Puig Major becomes a long final commitment—with an optional mostly downhill victory lap back to Pollença.",
    effort: "Respect the early climbing, fuel before Sóller, and ride Puig Major by feel rather than adrenaline.",
    map: assetUrl("assets/routes/stage-3-map.jpg"),
    profile: assetUrl("assets/routes/stage-3-profile.png"),
    officialUrl: "https://www.sacalobra.cc/stage/3/",
    videoUrl: "https://www.sacalobra.cc/stages/video/stage-3-1920.mp4",
    sourceNote: "The camp sheet, current SCCC stats, and official profile agree: 123 km / 2,349 m.",
    climbs: [
      {
        name: "Tofla",
        category: "Cat 4",
        distance: "1.50 km",
        gradient: "7%",
        strava: "https://www.strava.com/segments/684281",
      },
      {
        name: "Orient",
        category: "Cat 3",
        distance: "5.07 km",
        gradient: "5%",
        strava: "https://www.strava.com/segments/654280",
      },
      {
        name: "Honor",
        category: "Cat 4",
        distance: "1.55 km",
        gradient: "7%",
        strava: "https://www.strava.com/segments/10929855",
      },
      {
        name: "Sóller",
        category: "Cat 3",
        distance: "5.03 km",
        gradient: "5%",
        strava: "https://www.strava.com/segments/8107312",
      },
      {
        name: "Puig Major",
        category: "HC",
        distance: "14.2 km",
        gradient: "6%",
        strava: "https://www.strava.com/segments/649635",
      },
    ],
    publicRoutes: [
      {
        provider: "Wikiloc",
        label: "Pollença–Sóller–Puig Major",
        stats: "136 km · 2,284 m",
        match: "Closest public geometry · about 13 km longer",
        url: "https://es.wikiloc.com/rutas-ciclismo/pollenca-soller-puig-major-205815252",
      },
    ],
  },
  {
    id: 4,
    stageNumber: 4,
    date: "Wed 21 Oct",
    title: "Caffeine Ride",
    distance: "79 km",
    elevation: "620 m",
    duration: "2:45",
    difficulty: "Easy",
    motivation: "Spin, smile, sip.",
    routeLine: "Pollença · Sa Pobla · Inca · Cycling Planet, Alaró · Pollença",
    briefing:
      "The lightest day keeps the legs moving without another mountain battle. Smooth group miles lead to coffee and cake at Cycling Planet in Alaró, before rolling roads encourage a steady, social tempo back to Pollença.",
    effort: "Active recovery first. Keep the pressure light, eat the cake, and arrive home better than you left.",
    map: assetUrl("assets/routes/stage-4-map.jpg"),
    profile: assetUrl("assets/routes/stage-4-profile.png"),
    officialUrl: "https://www.sacalobra.cc/stage/4/",
    videoUrl: "https://www.sacalobra.cc/stages/video/stage-4-1920.mp4",
    sourceNote: "Camp sheet: 79 km / 620 m and lists Tofla. Current SCCC page: 79 km / 643 m and explicitly no major climbs. The older official profile reads about 84 km.",
    climbs: [],
    publicRoutes: [
      {
        provider: "Ride with GPS",
        label: "Alaró café corridor",
        stats: "98 km · 914 m",
        match: "Low match · longer, with different endpoints",
        url: "https://ridewithgps.com/routes/45507846?privacy_code=mhlTJT6XWviWITOtysDc3VUaibWS3lgI",
      },
    ],
  },
  {
    id: 6,
    stageNumber: 6,
    date: "Thu 22 Oct",
    title: "Sa Calobra",
    distance: "83 km",
    elevation: "1,962 m",
    duration: "4:30",
    difficulty: "Difficult",
    motivation: "Climb the coast.",
    routeLine: "Pollença · Femenia · Lluc · Coll dels Reis · Sa Calobra · Pollença",
    briefing:
      "Three Tramuntana approaches prime the legs before the road tips down through Sa Calobra’s famous hairpins. At the coast, the group turns around for a staggered-start time trial back up one of cycling’s great roads.",
    effort: "Stay controlled over Femenia and Lluc. The day is defined by what remains for the 9.44 km climb home.",
    map: assetUrl("assets/routes/stage-6-map.jpg"),
    profile: assetUrl("assets/routes/stage-6-profile.png"),
    officialUrl: "https://www.sacalobra.cc/stage/6/",
    videoUrl: "https://www.sacalobra.cc/stages/video/stage-6-1920.mp4",
    sourceNote: "The camp sheet, current SCCC stats, and official profile align: 83 km / 1,962 m.",
    climbs: [
      {
        name: "Femenia",
        category: "Cat 2",
        distance: "7.57 km",
        gradient: "6%",
        strava: "https://www.strava.com/segments/3620345",
      },
      {
        name: "Lluc",
        category: "Cat 3",
        distance: "3.22 km",
        gradient: "5%",
        strava: "https://www.strava.com/segments/626341",
      },
      {
        name: "Coll dels Reis",
        category: "Cat 4",
        distance: "2.37 km",
        gradient: "7%",
        strava: "https://www.strava.com/segments/626340",
      },
      {
        name: "Sa Calobra",
        category: "Cat 1",
        distance: "9.44 km",
        gradient: "7%",
        strava: "https://www.strava.com/segments/653262",
      },
    ],
    publicRoutes: [
      {
        provider: "Ride with GPS",
        label: "Sa Calobra mountain core",
        stats: "99 km · 2,012 m",
        match: "High partial match · extra Port de Pollença miles",
        url: "https://ridewithgps.com/routes/45507715?privacy_code=fiGyLEFhqygN06ZET7aO4XmdhXz3EXEx",
      },
      {
        provider: "Direct GPX",
        label: "Lluc–Sa Calobra out-and-back",
        stats: "46.7 km · 807 m",
        match: "Climb core only · omits the Femenia approach",
        url: "https://www.cyclinguk.org/sites/default/files/gpx/2020/01/2019-11-18_103708274_lluc_to_sa_calobra.gpx",
      },
    ],
  },
  {
    id: 5,
    stageNumber: 5,
    date: "Fri 23 Oct",
    title: "Cap de Formentor",
    distance: "89 km",
    elevation: "1,550 m",
    duration: "4:30",
    difficulty: "Intermediate",
    motivation: "Finish on the point.",
    routeLine: "Pollença · Albercutx · Formentor lighthouse · Victoria · Puig Maria",
    briefing:
      "Cycling Disneyland starts with the hidden road to Albercutx, then follows cliff roads and turquoise coves to the lighthouse. A green-jersey sprint, the narrow ramps of Victoria, and Puig Maria’s 20% sting make the final day anything but ceremonial.",
    effort: "Let the scenery set the pace early. Save one sharp acceleration for the sprint and one stubborn gear for Puig Maria.",
    map: assetUrl("assets/routes/stage-5-map.jpg"),
    profile: assetUrl("assets/routes/stage-5-profile.png"),
    officialUrl: "https://www.sacalobra.cc/stage/5/",
    videoUrl: "https://www.sacalobra.cc/stages/video/stage-5-1920.mp4",
    sourceNote: "Camp sheet: 1,550 m. Current SCCC route overview: 1,517 m. Distance remains 89 km.",
    climbs: [
      {
        name: "Mirador d’Albercutx",
        category: "Cat 2",
        distance: "5.46 km",
        gradient: "6%",
        strava: "https://www.strava.com/segments/654790",
      },
      {
        name: "Sa Creueta",
        category: "Cat 3",
        distance: "3.45 km",
        gradient: "5%",
        strava: "https://www.strava.com/segments/5978202",
      },
      {
        name: "Mirador de la Victoria",
        category: "Cat 4",
        distance: "1.32 km",
        gradient: "8%",
        strava: "https://www.strava.com/segments/24955066",
      },
      {
        name: "Puig Maria",
        category: "Cat 4",
        distance: "1.38 km",
        gradient: "10%",
        strava: "https://www.strava.com/segments/3774388",
      },
    ],
    publicRoutes: [
      {
        provider: "Ride with GPS",
        label: "Bay of Pollença / Formentor",
        stats: "77 km · 1,480 m",
        match: "Strong partial match · omits Puig Maria",
        url: "https://ridewithgps.com/routes/29010051",
      },
    ],
  },
];

export const weekTotals = {
  distance: "555 km",
  elevation: "8,795 m",
  rideDays: "6 ride days",
};
